version: '3.3'
services:
  mysql-database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: pedregulho
      MYSQL_USER: pedregulho_user
      MYSQL_PASSWORD: pedregulho_password
      MYSQL_ROOT_PASSWORD: pedregulho_password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  python-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
    - .:/app
    depends_on:
    - mysql-database
